//! Claude Code history: session summaries (cached) and transcript reading.
//!
//! Layout: `<projects>/<encoded-dir>/<sessionId>.jsonl`, subagents in
//! `<projects>/<encoded-dir>/<sessionId>/subagents/agent-<id>.jsonl` with an
//! `agent-<id>.meta.json` side file. Every file is opened through the
//! [`ConfigGuard`].

use std::collections::{HashMap, HashSet};
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Mutex;
use std::time::SystemTime;

use memchr::memmem;
use serde::Serialize;
use serde_json::Value;

use super::records::{tool_result_text, Content, FullBlock, Record, SummaryBlock};
use crate::error::{NativeError, NativeResult};
use crate::guard::ConfigGuard;
use crate::util::{is_safe_id, is_uuid, iso_time, one_line, truncate_marked};

pub const MAX_MESSAGES: usize = 1000;
pub const TOOL_INPUT_MAX: usize = 4 * 1024;
pub const TOOL_RESULT_MAX: usize = 8 * 1024;
/// Safety cap for a single text block (a pasted multi-MB log, for example).
pub const TEXT_MAX: usize = 256 * 1024;
pub const TITLE_MAX_CHARS: usize = 80;
const UNTITLED: &str = "Untitled session";
const READ_BUF: usize = 256 * 1024;

// ---------------------------------------------------------------- payloads

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub id: String,
    pub project_id: String,
    pub title: String,
    pub created_at: String,
    pub updated_at: String,
    pub message_count: u32,
    pub git_branch: Option<String>,
    pub model: Option<String>,
    pub subagent_count: u32,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SubagentInfo {
    pub id: String,
    pub agent_type: Option<String>,
    pub description: Option<String>,
    pub tool_use_id: Option<String>,
    pub message_count: u32,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(
    tag = "type",
    rename_all = "snake_case",
    rename_all_fields = "camelCase"
)]
pub enum Block {
    Text {
        text: String,
    },
    ToolUse {
        id: String,
        name: String,
        input: String,
    },
    ToolResult {
        tool_use_id: String,
        is_error: bool,
        text: String,
    },
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User,
    Assistant,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TranscriptMessage {
    pub id: String,
    pub role: Role,
    pub timestamp: Option<String>,
    pub model: Option<String>,
    pub blocks: Vec<Block>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Transcript {
    pub session: SessionInfo,
    pub messages: Vec<TranscriptMessage>,
    pub subagents: Vec<SubagentInfo>,
    pub truncated: bool,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SubagentTranscript {
    pub subagent: SubagentInfo,
    pub messages: Vec<TranscriptMessage>,
    pub truncated: bool,
}

// ---------------------------------------------------------------- classification

/// Cleans a user text block. Returns `None` for wrapper/meta text that is not
/// shown (command output, caveats, system reminders); slash-command wrappers
/// become `/name args`.
pub fn clean_user_text(text: &str) -> Option<String> {
    let t = text.trim();
    if t.is_empty() {
        return None;
    }
    if t.contains("<command-name>") {
        let name = between(t, "<command-name>", "</command-name>")?.trim();
        let args = between(t, "<command-args>", "</command-args>")
            .unwrap_or_default()
            .trim();
        let name = if name.starts_with('/') {
            name.to_owned()
        } else {
            format!("/{name}")
        };
        return Some(if args.is_empty() {
            name
        } else {
            format!("{name} {args}")
        });
    }
    const HIDDEN: &[&str] = &[
        "<local-command-stdout>",
        "<local-command-stderr>",
        "<local-command-caveat>",
        "<command-message>",
        "<system-reminder>",
        "Caveat: The messages below were generated by the user while running local commands",
    ];
    if HIDDEN.iter().any(|h| t.starts_with(h)) {
        return None;
    }
    Some(t.to_owned())
}

fn between<'a>(s: &'a str, open: &str, close: &str) -> Option<&'a str> {
    let start = s.find(open)? + open.len();
    let end = s[start..].find(close)? + start;
    Some(&s[start..end])
}

/// Records that are never shown: meta, compact summaries and (in a main
/// session file) sidechain records of older Claude Code versions.
fn skip_record<B>(r: &Record<B>, include_sidechain: bool) -> bool {
    r.is_meta.0 || r.is_compact_summary.0 || (!include_sidechain && r.is_sidechain.0)
}

// ---------------------------------------------------------------- summary pass

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Summary {
    pub title: String,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub message_count: u32,
    pub git_branch: Option<String>,
    pub model: Option<String>,
    pub cwd: Option<String>,
}

const INTERESTING: &[&[u8]] = &[
    b"\"type\":\"user\"",
    b"\"type\":\"assistant\"",
    b"\"type\":\"custom-title\"",
    b"\"type\":\"ai-title\"",
    b"\"type\":\"summary\"",
];

fn interesting(line: &[u8]) -> bool {
    INTERESTING.iter().any(|p| memmem::find(line, p).is_some())
}

/// Calls `f` for every non-empty line of `reader` (raw bytes, no UTF-8 check).
fn for_each_line<R: BufRead>(mut reader: R, mut f: impl FnMut(&[u8])) {
    let mut buf = Vec::with_capacity(64 * 1024);
    loop {
        buf.clear();
        match reader.read_until(b'\n', &mut buf) {
            Ok(0) | Err(_) => break,
            Ok(_) => {
                let line = buf.trim_ascii();
                if !line.is_empty() {
                    f(line);
                }
            }
        }
    }
}

/// Single cheap pass over a transcript. `None` = no user/assistant message.
pub fn summarize<R: BufRead>(reader: R, include_sidechain: bool) -> Option<Summary> {
    let mut custom_title: Option<String> = None;
    let mut ai_title: Option<String> = None;
    let mut summary_title: Option<String> = None;
    let mut first_user: Option<String> = None;
    let mut created_at: Option<String> = None;
    let mut updated_at: Option<String> = None;
    let mut git_branch: Option<String> = None;
    let mut model: Option<String> = None;
    let mut cwd: Option<String> = None;
    let mut user_count = 0u32;
    let mut assistant_ids: HashSet<String> = HashSet::new();
    let mut anon_assistant = 0u32;

    for_each_line(reader, |line| {
        if !interesting(line) {
            return;
        }
        let Ok(r) = serde_json::from_slice::<Record<SummaryBlock>>(line) else {
            return;
        };
        match r.kind.get() {
            Some("custom-title") => {
                if let Some(t) = r.custom_title.non_empty() {
                    custom_title = Some(t.to_owned());
                }
            }
            Some("ai-title") => {
                if let Some(t) = r.ai_title.non_empty() {
                    ai_title = Some(t.to_owned());
                }
            }
            Some("summary") => {
                if let Some(t) = r.summary.non_empty() {
                    summary_title = Some(t.to_owned());
                }
            }
            Some(kind @ ("user" | "assistant")) => {
                if skip_record(&r, include_sidechain) {
                    return;
                }
                let Some(msg) = r.message.as_ref() else {
                    return;
                };
                let displayable = if kind == "user" {
                    match &msg.content {
                        Some(Content::Text(t)) => {
                            let cleaned = clean_user_text(t);
                            if first_user.is_none() {
                                first_user.clone_from(&cleaned);
                            }
                            cleaned.is_some()
                        }
                        Some(Content::Blocks(blocks)) => {
                            let mut any = false;
                            for b in blocks {
                                match b.kind.get() {
                                    Some("text") => {
                                        let cleaned = b.text.get().and_then(clean_user_text);
                                        if first_user.is_none() {
                                            first_user.clone_from(&cleaned);
                                        }
                                        any |= cleaned.is_some();
                                    }
                                    Some("tool_result" | "image") => any = true,
                                    _ => {}
                                }
                            }
                            any
                        }
                        None => false,
                    }
                } else {
                    let shown = match &msg.content {
                        Some(Content::Text(t)) => !t.trim().is_empty(),
                        Some(Content::Blocks(blocks)) => {
                            blocks.iter().any(|b| match b.kind.get() {
                                Some("text") => b.text.non_empty().is_some(),
                                Some("tool_use") => true,
                                _ => false,
                            })
                        }
                        None => false,
                    };
                    if let Some(m) = msg.model.non_empty().filter(|m| *m != "<synthetic>") {
                        model = Some(m.to_owned());
                    }
                    shown
                };
                if !displayable {
                    return;
                }
                if kind == "user" {
                    user_count += 1;
                } else {
                    match msg.id.non_empty() {
                        Some(id) => {
                            if !assistant_ids.contains(id) {
                                assistant_ids.insert(id.to_owned());
                            }
                        }
                        None => anon_assistant += 1,
                    }
                }
                if let Some(ts) = r.timestamp.non_empty() {
                    if created_at.is_none() {
                        created_at = Some(ts.to_owned());
                    }
                    updated_at = Some(ts.to_owned());
                }
                if let Some(b) = r.git_branch.non_empty() {
                    git_branch = Some(b.to_owned());
                }
                if let Some(c) = r.cwd.non_empty() {
                    cwd = Some(c.to_owned());
                }
            }
            _ => {}
        }
    });

    let count = user_count + assistant_ids.len() as u32 + anon_assistant;
    if count == 0 {
        return None;
    }
    let title = custom_title
        .or(ai_title)
        .or(summary_title)
        .or(first_user)
        .map(|t| one_line(&t, TITLE_MAX_CHARS))
        .filter(|t| !t.is_empty())
        .unwrap_or_else(|| UNTITLED.to_owned());
    Some(Summary {
        title,
        created_at,
        updated_at,
        message_count: count,
        git_branch,
        model,
        cwd,
    })
}

// ---------------------------------------------------------------- full pass

/// Reads a transcript into display messages (last [`MAX_MESSAGES`]).
pub fn read_messages<R: BufRead>(
    reader: R,
    include_sidechain: bool,
) -> (Vec<TranscriptMessage>, bool) {
    let mut messages: Vec<TranscriptMessage> = Vec::new();
    let mut by_api_id: HashMap<String, usize> = HashMap::new();
    let mut line_no = 0usize;

    for_each_line(reader, |line| {
        line_no += 1;
        if memmem::find(line, b"\"type\":\"user\"").is_none()
            && memmem::find(line, b"\"type\":\"assistant\"").is_none()
        {
            return;
        }
        let Ok(r) = serde_json::from_slice::<Record<FullBlock>>(line) else {
            return;
        };
        let role = match r.kind.get() {
            Some("user") => Role::User,
            Some("assistant") => Role::Assistant,
            _ => return,
        };
        if skip_record(&r, include_sidechain) {
            return;
        }
        let Some(msg) = r.message else {
            return;
        };
        let blocks = match role {
            Role::User => user_blocks(msg.content),
            Role::Assistant => assistant_blocks(msg.content),
        };
        if blocks.is_empty() {
            return;
        }
        let timestamp = r.timestamp.non_empty().map(str::to_owned);
        if role == Role::Assistant {
            let api_id = msg.id.non_empty().map(str::to_owned);
            if let Some(idx) = api_id.as_ref().and_then(|id| by_api_id.get(id)) {
                if let Some(existing) = messages.get_mut(*idx) {
                    existing.blocks.extend(blocks);
                    return;
                }
            }
            let id = api_id
                .clone()
                .or_else(|| r.uuid.non_empty().map(str::to_owned))
                .unwrap_or_else(|| format!("line-{line_no}"));
            if let Some(api_id) = api_id {
                by_api_id.insert(api_id, messages.len());
            }
            messages.push(TranscriptMessage {
                id,
                role,
                timestamp,
                model: msg
                    .model
                    .non_empty()
                    .filter(|m| *m != "<synthetic>")
                    .map(str::to_owned),
                blocks,
            });
        } else {
            messages.push(TranscriptMessage {
                id: r
                    .uuid
                    .non_empty()
                    .map(str::to_owned)
                    .unwrap_or_else(|| format!("line-{line_no}")),
                role,
                timestamp,
                model: None,
                blocks,
            });
        }
    });

    let truncated = messages.len() > MAX_MESSAGES;
    if truncated {
        messages.drain(..messages.len() - MAX_MESSAGES);
    }
    (messages, truncated)
}

fn text_block(text: &str) -> Block {
    Block::Text {
        text: truncate_marked(text, TEXT_MAX),
    }
}

fn user_blocks(content: Option<Content<FullBlock>>) -> Vec<Block> {
    match content {
        Some(Content::Text(t)) => clean_user_text(&t)
            .map(|t| text_block(&t))
            .into_iter()
            .collect(),
        Some(Content::Blocks(blocks)) => blocks
            .into_iter()
            .filter_map(|b| match b.kind.get() {
                Some("text") => b
                    .text
                    .get()
                    .and_then(clean_user_text)
                    .map(|t| text_block(&t)),
                Some("image") => Some(text_block("[image]")),
                Some("tool_result") => Some(Block::ToolResult {
                    tool_use_id: b.tool_use_id.get().unwrap_or_default().to_owned(),
                    is_error: b.is_error.0,
                    text: truncate_marked(&tool_result_text(b.content.as_ref()), TOOL_RESULT_MAX),
                }),
                _ => None,
            })
            .collect(),
        None => Vec::new(),
    }
}

fn assistant_blocks(content: Option<Content<FullBlock>>) -> Vec<Block> {
    match content {
        Some(Content::Text(t)) if !t.trim().is_empty() => vec![text_block(&t)],
        Some(Content::Blocks(blocks)) => blocks
            .into_iter()
            .filter_map(|b| match b.kind.get() {
                Some("text") => b.text.non_empty().map(text_block),
                Some("tool_use") => Some(Block::ToolUse {
                    id: b.id.get().unwrap_or_default().to_owned(),
                    name: b.name.get().unwrap_or_default().to_owned(),
                    input: truncate_marked(
                        b.input.as_ref().map_or("{}", |r| r.get()),
                        TOOL_INPUT_MAX,
                    ),
                }),
                _ => None, // thinking, redacted_thinking, server tool blocks
            })
            .collect(),
        _ => Vec::new(),
    }
}

// ---------------------------------------------------------------- files + cache

#[derive(Debug, Clone)]
pub struct FileMeta {
    pub path: PathBuf,
    pub len: u64,
    pub mtime: SystemTime,
}

impl FileMeta {
    pub fn of(path: PathBuf, meta: &std::fs::Metadata) -> Self {
        Self {
            path,
            len: meta.len(),
            mtime: meta.modified().unwrap_or(SystemTime::UNIX_EPOCH),
        }
    }
}

type CacheEntry = (u64, SystemTime, Option<Summary>);

/// Summary cache keyed by path and validated by (length, mtime).
#[derive(Default)]
pub struct HistoryCache {
    map: Mutex<HashMap<PathBuf, CacheEntry>>,
}

impl HistoryCache {
    /// `Some(summary-or-empty)` when cached and still valid.
    pub fn get(&self, f: &FileMeta) -> Option<Option<Summary>> {
        let map = self.map.lock().ok()?;
        map.get(&f.path)
            .filter(|(len, mtime, _)| *len == f.len && *mtime == f.mtime)
            .map(|(_, _, s)| s.clone())
    }

    fn put(&self, f: &FileMeta, s: Option<Summary>) {
        if let Ok(mut map) = self.map.lock() {
            map.insert(f.path.clone(), (f.len, f.mtime, s));
        }
    }

    pub fn summarize_file(
        &self,
        guard: &ConfigGuard,
        f: &FileMeta,
        sidechain: bool,
    ) -> Option<Summary> {
        if let Some(hit) = self.get(f) {
            return hit;
        }
        let summary = match guard.open(&f.path) {
            Ok(file) => summarize(BufReader::with_capacity(READ_BUF, file), sidechain),
            Err(_) => return None, // not cached: may be transient
        };
        self.put(f, summary.clone());
        summary
    }

    /// Summarizes many files in parallel (bounded worker threads).
    pub fn summarize_many(
        &self,
        guard: &ConfigGuard,
        files: &[FileMeta],
        sidechain: bool,
    ) -> Vec<Option<Summary>> {
        let results: Vec<Mutex<Option<Summary>>> = files.iter().map(|_| Mutex::new(None)).collect();
        let next = AtomicUsize::new(0);
        let workers = std::thread::available_parallelism()
            .map_or(4, |n| n.get())
            .clamp(1, 8)
            .min(files.len().max(1));
        std::thread::scope(|scope| {
            for _ in 0..workers {
                scope.spawn(|| loop {
                    let i = next.fetch_add(1, Ordering::Relaxed);
                    let Some(f) = files.get(i) else { break };
                    let s = self.summarize_file(guard, f, sidechain);
                    if let Ok(mut slot) = results[i].lock() {
                        *slot = s;
                    }
                });
            }
        });
        results
            .into_iter()
            .map(|m| m.into_inner().ok().flatten())
            .collect()
    }
}

/// Session transcript files (`<uuid>.jsonl`) of one history directory, plus
/// the names of its sub-directories (used to find subagents cheaply).
pub fn list_session_files(
    guard: &ConfigGuard,
    dir: &Path,
) -> NativeResult<(Vec<FileMeta>, HashSet<String>)> {
    let mut files = Vec::new();
    let mut subdirs = HashSet::new();
    for entry in guard.read_dir(dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let Ok(ft) = entry.file_type() else { continue };
        if ft.is_dir() {
            subdirs.insert(name);
        } else if ft.is_file() {
            if let Some(stem) = name.strip_suffix(".jsonl") {
                if is_uuid(stem) {
                    if let Ok(meta) = entry.metadata() {
                        files.push(FileMeta::of(entry.path(), &meta));
                    }
                }
            }
        }
    }
    Ok((files, subdirs))
}

fn session_id_of(f: &FileMeta) -> String {
    f.path
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default()
}

fn count_subagents(guard: &ConfigGuard, session_dir: &Path) -> u32 {
    let sub = session_dir.join("subagents");
    let Ok(rd) = guard.read_dir(&sub) else {
        return 0;
    };
    rd.flatten()
        .filter(|e| agent_id_of(&e.file_name().to_string_lossy()).is_some())
        .count() as u32
}

/// `agent-<id>.jsonl` -> `<id>`.
fn agent_id_of(file_name: &str) -> Option<String> {
    let id = file_name.strip_prefix("agent-")?.strip_suffix(".jsonl")?;
    is_safe_id(id).then(|| id.to_owned())
}

fn session_info(project_id: &str, f: &FileMeta, s: &Summary, subagent_count: u32) -> SessionInfo {
    let mtime = iso_time(f.mtime);
    SessionInfo {
        id: session_id_of(f),
        project_id: project_id.to_owned(),
        title: s.title.clone(),
        created_at: s.created_at.clone().unwrap_or_else(|| mtime.clone()),
        updated_at: s.updated_at.clone().unwrap_or(mtime),
        message_count: s.message_count,
        git_branch: s.git_branch.clone(),
        model: s.model.clone(),
        subagent_count,
    }
}

/// Sessions of the given history directories, newest first.
pub fn sessions_list(
    guard: &ConfigGuard,
    cache: &HistoryCache,
    project_id: &str,
    history_dirs: &[PathBuf],
) -> NativeResult<Vec<SessionInfo>> {
    let mut out = Vec::new();
    let mut seen = HashSet::new();
    for dir in history_dirs {
        let (files, subdirs) = match list_session_files(guard, dir) {
            Ok(v) => v,
            Err(e) if e.code == "not_found" => continue,
            Err(e) => return Err(e),
        };
        let summaries = cache.summarize_many(guard, &files, false);
        for (f, s) in files.iter().zip(summaries) {
            let Some(s) = s else { continue };
            let id = session_id_of(f);
            if !seen.insert(id.clone()) {
                continue;
            }
            let subagents = if subdirs.contains(&id) {
                count_subagents(guard, &dir.join(&id))
            } else {
                0
            };
            out.push(session_info(project_id, f, &s, subagents));
        }
    }
    out.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
    Ok(out)
}

fn find_session_file(
    guard: &ConfigGuard,
    history_dirs: &[PathBuf],
    session_id: &str,
) -> NativeResult<(PathBuf, FileMeta)> {
    if !is_uuid(session_id) {
        return Err(NativeError::invalid("invalid session id"));
    }
    for dir in history_dirs {
        let path = dir.join(format!("{session_id}.jsonl"));
        if let Ok(canonical) = guard.check(&path) {
            let meta = std::fs::metadata(&canonical).map_err(|e| NativeError::io("session", &e))?;
            return Ok((dir.clone(), FileMeta::of(path, &meta)));
        }
    }
    Err(NativeError::not_found("session not found"))
}

pub fn session_read(
    guard: &ConfigGuard,
    cache: &HistoryCache,
    project_id: &str,
    history_dirs: &[PathBuf],
    session_id: &str,
) -> NativeResult<Transcript> {
    let (dir, f) = find_session_file(guard, history_dirs, session_id)?;
    let file = guard.open(&f.path)?;
    let (messages, truncated) = read_messages(BufReader::with_capacity(READ_BUF, file), false);
    let summary = cache
        .summarize_file(guard, &f, false)
        .unwrap_or_else(|| Summary {
            title: UNTITLED.to_owned(),
            created_at: None,
            updated_at: None,
            message_count: 0,
            git_branch: None,
            model: None,
            cwd: None,
        });
    let subagents = list_subagents(guard, cache, &dir.join(session_id));
    let session = session_info(project_id, &f, &summary, subagents.len() as u32);
    Ok(Transcript {
        session,
        messages,
        subagents,
        truncated,
    })
}

#[derive(Debug, Default)]
struct AgentMeta {
    agent_type: Option<String>,
    description: Option<String>,
    tool_use_id: Option<String>,
}

fn read_agent_meta(guard: &ConfigGuard, path: &Path) -> AgentMeta {
    let Ok(text) = guard.read_small(path, 64 * 1024) else {
        return AgentMeta::default();
    };
    let Ok(v) = serde_json::from_str::<Value>(&text) else {
        return AgentMeta::default();
    };
    let s = |k: &str| {
        v.get(k)
            .and_then(Value::as_str)
            .filter(|s| !s.trim().is_empty())
            .map(str::to_owned)
    };
    AgentMeta {
        agent_type: s("agentType"),
        description: s("description").map(|d| one_line(&d, 200)),
        tool_use_id: s("toolUseId"),
    }
}

fn subagent_info(
    guard: &ConfigGuard,
    cache: &HistoryCache,
    sub_dir: &Path,
    id: &str,
    f: &FileMeta,
) -> SubagentInfo {
    let meta = read_agent_meta(guard, &sub_dir.join(format!("agent-{id}.meta.json")));
    let summary = cache.summarize_file(guard, f, true);
    SubagentInfo {
        id: id.to_owned(),
        agent_type: meta.agent_type,
        description: meta.description,
        tool_use_id: meta.tool_use_id,
        message_count: summary.as_ref().map_or(0, |s| s.message_count),
        updated_at: summary
            .and_then(|s| s.updated_at)
            .unwrap_or_else(|| iso_time(f.mtime)),
    }
}

/// Subagents of a session (`<session_dir>/subagents`), oldest first.
pub fn list_subagents(
    guard: &ConfigGuard,
    cache: &HistoryCache,
    session_dir: &Path,
) -> Vec<SubagentInfo> {
    let sub_dir = session_dir.join("subagents");
    let Ok(rd) = guard.read_dir(&sub_dir) else {
        return Vec::new();
    };
    let mut items: Vec<(String, FileMeta)> = rd
        .flatten()
        .filter_map(|e| {
            let id = agent_id_of(&e.file_name().to_string_lossy())?;
            let meta = e.metadata().ok()?;
            meta.is_file().then(|| (id, FileMeta::of(e.path(), &meta)))
        })
        .collect();
    items.sort_by(|a, b| a.1.mtime.cmp(&b.1.mtime).then_with(|| a.0.cmp(&b.0)));
    items
        .iter()
        .map(|(id, f)| subagent_info(guard, cache, &sub_dir, id, f))
        .collect()
}

pub fn subagent_read(
    guard: &ConfigGuard,
    cache: &HistoryCache,
    history_dirs: &[PathBuf],
    session_id: &str,
    agent_id: &str,
) -> NativeResult<SubagentTranscript> {
    if !is_safe_id(agent_id) {
        return Err(NativeError::invalid("invalid agent id"));
    }
    let (dir, _) = find_session_file(guard, history_dirs, session_id)?;
    let sub_dir = dir.join(session_id).join("subagents");
    let path = sub_dir.join(format!("agent-{agent_id}.jsonl"));
    let canonical = guard.check(&path).map_err(|e| {
        if e.code == "not_found" {
            NativeError::not_found("subagent not found")
        } else {
            e
        }
    })?;
    let meta = std::fs::metadata(&canonical).map_err(|e| NativeError::io("subagent", &e))?;
    let f = FileMeta::of(path, &meta);
    let file = guard.open(&f.path)?;
    let (messages, truncated) = read_messages(BufReader::with_capacity(READ_BUF, file), true);
    Ok(SubagentTranscript {
        subagent: subagent_info(guard, cache, &sub_dir, agent_id, &f),
        messages,
        truncated,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    const S1: &str = "11111111-2222-3333-4444-555555555555";

    fn fixture() -> String {
        [
            r#"{"type":"queue-operation","operation":"enqueue","timestamp":"2026-01-01T00:00:00.000Z","sessionId":"s"}"#,
            r#"{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":"Please   fix the\nbug in main.rs"},"uuid":"u1","timestamp":"2026-01-01T00:00:01.000Z","cwd":"C:\\work\\demo","gitBranch":"main","sessionId":"s"}"#,
            r#"{"parentUuid":"u1","isSidechain":false,"type":"user","isMeta":true,"message":{"role":"user","content":"<system-reminder>hidden</system-reminder>"},"uuid":"u-meta","timestamp":"2026-01-01T00:00:01.500Z"}"#,
            r#"{"type":"attachment","attachment":{"type":"user","content":"ignored"},"uuid":"att"}"#,
            r#"{"parentUuid":"u1","isSidechain":false,"type":"assistant","message":{"id":"msg_A","role":"assistant","model":"claude-opus-4","content":[{"type":"thinking","thinking":"secret thoughts","signature":"x"}]},"uuid":"a0","timestamp":"2026-01-01T00:00:02.000Z"}"#,
            r#"{"parentUuid":"a0","isSidechain":false,"type":"assistant","message":{"id":"msg_A","role":"assistant","model":"claude-opus-4","content":[{"type":"text","text":"Looking at it."}]},"uuid":"a1","timestamp":"2026-01-01T00:00:02.100Z"}"#,
            r#"{"parentUuid":"a1","isSidechain":false,"type":"assistant","message":{"id":"msg_A","role":"assistant","model":"claude-opus-4","content":[{"type":"tool_use","id":"toolu_1","name":"Read","input":{"file_path":"src/main.rs"}}]},"uuid":"a2","timestamp":"2026-01-01T00:00:02.200Z"}"#,
            r#"{"parentUuid":"a2","isSidechain":false,"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_1","type":"tool_result","content":"fn main() {}","is_error":false}]},"uuid":"u2","timestamp":"2026-01-01T00:00:03.000Z","toolUseResult":{"big":"ignored"}}"#,
            r#"{"parentUuid":"u2","isSidechain":false,"type":"assistant","message":{"id":"msg_B","role":"assistant","model":"claude-opus-4","content":[{"type":"tool_use","id":"toolu_2","name":"Task","input":{"subagent_type":"general-purpose","description":"Explore"}}]},"uuid":"a3","timestamp":"2026-01-01T00:00:04.000Z"}"#,
            r#"{"parentUuid":"a3","isSidechain":false,"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_2","type":"tool_result","content":[{"type":"text","text":"done"}],"is_error":true}]},"uuid":"u3","timestamp":"2026-01-01T00:00:05.000Z"}"#,
            r#"{"parentUuid":"u3","isSidechain":true,"type":"user","message":{"role":"user","content":"old sidechain record"},"uuid":"side","timestamp":"2026-01-01T00:00:05.500Z"}"#,
            r#"{"type":"user","message":{"role":"user","content":"<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>"},"uuid":"u4","timestamp":"2026-01-01T00:00:06.000Z"}"#,
            r#"{"type":"user","message":{"role":"user","content":"<local-command-stdout>Set model</local-command-stdout>"},"uuid":"u5","timestamp":"2026-01-01T00:00:06.500Z"}"#,
            r#"{"type":"assistant","message":{"id":"msg_C","model":"<synthetic>","content":[{"type":"text","text":"No response requested."}]},"uuid":"a4","timestamp":"2026-01-01T00:00:07.000Z"}"#,
            r#"{"type":"ai-title","aiTitle":"Fix main.rs bug","sessionId":"s"}"#,
            "this is not json",
            r#"{"type":"user","message":"#,
            "",
        ]
        .join("\n")
    }

    #[test]
    fn summary_counts_titles_and_metadata() {
        let s = summarize(Cursor::new(fixture()), false).expect("non-empty");
        // users: u1, u2, u3, u4 ; assistants: msg_A, msg_B, msg_C
        assert_eq!(s.message_count, 7);
        assert_eq!(s.title, "Fix main.rs bug");
        assert_eq!(s.created_at.as_deref(), Some("2026-01-01T00:00:01.000Z"));
        assert_eq!(s.updated_at.as_deref(), Some("2026-01-01T00:00:07.000Z"));
        assert_eq!(s.git_branch.as_deref(), Some("main"));
        assert_eq!(s.model.as_deref(), Some("claude-opus-4"));
        assert_eq!(s.cwd.as_deref(), Some("C:\\work\\demo"));
    }

    #[test]
    fn title_precedence() {
        let base = fixture();
        let custom = format!(
            "{base}\n{}",
            r#"{"type":"custom-title","customTitle":"My title","sessionId":"s"}"#
        );
        assert_eq!(
            summarize(Cursor::new(custom), false).expect("s").title,
            "My title"
        );

        let no_titles: String = base
            .lines()
            .filter(|l| !l.contains("ai-title"))
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(
            summarize(Cursor::new(no_titles), false).expect("s").title,
            "Please fix the bug in main.rs"
        );

        let long = format!(
            r#"{{"type":"user","message":{{"content":"{}"}},"uuid":"x"}}"#,
            "word ".repeat(40)
        );
        let t = summarize(Cursor::new(long), false).expect("s").title;
        assert_eq!(t.chars().count(), TITLE_MAX_CHARS);
        assert!(t.ends_with('\u{2026}'));
    }

    #[test]
    fn empty_sessions_are_none() {
        let only_meta = [
            r#"{"type":"queue-operation","operation":"enqueue"}"#,
            r#"{"type":"user","isMeta":true,"message":{"content":"x"},"uuid":"m"}"#,
            r#"{"type":"custom-title","customTitle":"t"}"#,
        ]
        .join("\n");
        assert!(summarize(Cursor::new(only_meta), false).is_none());
        assert!(summarize(Cursor::new(""), false).is_none());
    }

    #[test]
    fn full_read_merges_and_filters() {
        let (msgs, truncated) = read_messages(Cursor::new(fixture()), false);
        assert!(!truncated);
        let ids: Vec<&str> = msgs.iter().map(|m| m.id.as_str()).collect();
        assert_eq!(ids, ["u1", "msg_A", "u2", "msg_B", "u3", "u4", "msg_C"]);

        let u1 = &msgs[0];
        assert_eq!(u1.role, Role::User);
        assert_eq!(
            u1.blocks,
            vec![Block::Text {
                text: "Please   fix the\nbug in main.rs".into()
            }]
        );

        let a = &msgs[1];
        assert_eq!(a.role, Role::Assistant);
        assert_eq!(a.model.as_deref(), Some("claude-opus-4"));
        // The thinking-only record is dropped; the first shown block sets the time.
        assert_eq!(a.timestamp.as_deref(), Some("2026-01-01T00:00:02.100Z"));
        assert_eq!(
            a.blocks,
            vec![
                Block::Text {
                    text: "Looking at it.".into()
                },
                Block::ToolUse {
                    id: "toolu_1".into(),
                    name: "Read".into(),
                    input: r#"{"file_path":"src/main.rs"}"#.into()
                }
            ]
        );
        assert_eq!(
            msgs[2].blocks,
            vec![Block::ToolResult {
                tool_use_id: "toolu_1".into(),
                is_error: false,
                text: "fn main() {}".into()
            }]
        );
        assert_eq!(
            msgs[4].blocks,
            vec![Block::ToolResult {
                tool_use_id: "toolu_2".into(),
                is_error: true,
                text: "done".into()
            }]
        );
        assert_eq!(
            msgs[5].blocks,
            vec![Block::Text {
                text: "/model opus".into()
            }]
        );
        assert_eq!(msgs[6].model, None, "synthetic model hidden");

        // Serialized shape matches the contract.
        let json = serde_json::to_value(&msgs[2]).expect("json");
        assert_eq!(json["blocks"][0]["type"], "tool_result");
        assert_eq!(json["blocks"][0]["toolUseId"], "toolu_1");
        assert_eq!(json["blocks"][0]["isError"], false);
        let json = serde_json::to_value(&msgs[1]).expect("json");
        assert_eq!(json["blocks"][1]["type"], "tool_use");
        assert_eq!(json["role"], "assistant");

        // Subagent files are all sidechain records: included on request.
        let (msgs, _) = read_messages(Cursor::new(fixture()), true);
        assert!(msgs.iter().any(|m| m.id == "side"));
    }

    #[test]
    fn truncation_of_inputs_results_and_message_count() {
        let big_input = "x".repeat(10_000);
        let big_result = "y".repeat(20_000);
        let mut lines = vec![
            format!(
                r#"{{"type":"assistant","message":{{"id":"m","content":[{{"type":"tool_use","id":"t","name":"Write","input":{{"content":"{big_input}"}}}}]}},"uuid":"a"}}"#
            ),
            format!(
                r#"{{"type":"user","message":{{"content":[{{"type":"tool_result","tool_use_id":"t","content":"{big_result}"}}]}},"uuid":"r"}}"#
            ),
        ];
        for i in 0..1100 {
            lines.push(format!(
                r#"{{"type":"user","message":{{"content":"msg {i}"}},"uuid":"u{i}"}}"#
            ));
        }
        let (msgs, truncated) = read_messages(Cursor::new(lines[..2].join("\n")), false);
        assert!(!truncated);
        match &msgs[0].blocks[0] {
            Block::ToolUse { input, .. } => {
                assert!(input.len() <= TOOL_INPUT_MAX + 32);
                assert!(input.ends_with("[truncated]"));
            }
            other => panic!("unexpected {other:?}"),
        }
        match &msgs[1].blocks[0] {
            Block::ToolResult { text, .. } => {
                assert!(text.len() <= TOOL_RESULT_MAX + 32);
                assert!(text.ends_with("[truncated]"));
            }
            other => panic!("unexpected {other:?}"),
        }

        let (msgs, truncated) = read_messages(Cursor::new(lines.join("\n")), false);
        assert!(truncated);
        assert_eq!(msgs.len(), MAX_MESSAGES);
        assert_eq!(msgs.last().map(|m| m.id.as_str()), Some("u1099"));
    }

    #[test]
    fn clean_user_text_rules() {
        assert_eq!(clean_user_text("  hi "), Some("hi".into()));
        assert_eq!(clean_user_text("   "), None);
        assert_eq!(
            clean_user_text("<local-command-caveat>x</local-command-caveat>"),
            None
        );
        assert_eq!(
            clean_user_text(
                "<command-message>clear</command-message>\n<command-name>/clear</command-name>"
            ),
            Some("/clear".into())
        );
        assert_eq!(
            clean_user_text(
                "<command-name>review</command-name><command-args>pr 12</command-args>"
            ),
            Some("/review pr 12".into())
        );
    }

    fn write_project(cfg: &Path) -> PathBuf {
        let dir = cfg.join("projects").join("C--work-demo");
        let sub = dir.join(S1).join("subagents");
        std::fs::create_dir_all(&sub).expect("mkdir");
        std::fs::write(dir.join(format!("{S1}.jsonl")), fixture()).expect("write");
        std::fs::write(
            dir.join("99999999-2222-3333-4444-555555555555.jsonl"),
            r#"{"type":"queue-operation","operation":"enqueue"}"#,
        )
        .expect("write");
        std::fs::write(dir.join("not-a-session.jsonl"), fixture()).expect("write");
        std::fs::write(
            sub.join("agent-a1b2c3.jsonl"),
            [
                r#"{"isSidechain":true,"type":"user","message":{"role":"user","content":"Explore the repo"},"uuid":"s1","timestamp":"2026-01-01T00:00:04.100Z"}"#,
                r#"{"isSidechain":true,"type":"assistant","message":{"id":"msg_S","model":"claude-haiku","content":[{"type":"text","text":"Found it"}]},"uuid":"s2","timestamp":"2026-01-01T00:00:04.900Z"}"#,
            ]
            .join("\n"),
        )
        .expect("write");
        std::fs::write(
            sub.join("agent-a1b2c3.meta.json"),
            r#"{"agentType":"general-purpose","description":"Explore","toolUseId":"toolu_2","spawnDepth":1}"#,
        )
        .expect("write");
        dir
    }

    #[test]
    fn sessions_and_subagents_end_to_end() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let cfg = tmp.path().join(".claude");
        let dir = write_project(&cfg);
        let guard = ConfigGuard::new(&cfg, None).expect("guard");
        let cache = HistoryCache::default();
        let dirs = vec![dir];

        let list = sessions_list(&guard, &cache, "C--work-demo", &dirs).expect("list");
        assert_eq!(list.len(), 1, "empty and non-uuid sessions are skipped");
        let s = &list[0];
        assert_eq!(s.id, S1);
        assert_eq!(s.project_id, "C--work-demo");
        assert_eq!(s.subagent_count, 1);
        assert_eq!(s.message_count, 7);
        let json = serde_json::to_value(s).expect("json");
        assert!(json.get("subagentCount").is_some() && json.get("gitBranch").is_some());

        // Cached second call returns the same.
        assert_eq!(
            sessions_list(&guard, &cache, "C--work-demo", &dirs).expect("list"),
            list
        );

        let t = session_read(&guard, &cache, "C--work-demo", &dirs, S1).expect("read");
        assert_eq!(t.messages.len(), 7);
        assert_eq!(t.subagents.len(), 1);
        let sa = &t.subagents[0];
        assert_eq!(sa.id, "a1b2c3");
        assert_eq!(sa.agent_type.as_deref(), Some("general-purpose"));
        assert_eq!(sa.description.as_deref(), Some("Explore"));
        assert_eq!(sa.tool_use_id.as_deref(), Some("toolu_2"));
        assert_eq!(sa.message_count, 2);
        assert_eq!(sa.updated_at, "2026-01-01T00:00:04.900Z");

        let st = subagent_read(&guard, &cache, &dirs, S1, "a1b2c3").expect("subagent");
        assert_eq!(st.messages.len(), 2);
        assert_eq!(st.subagent.agent_type.as_deref(), Some("general-purpose"));

        assert_eq!(
            session_read(&guard, &cache, "p", &dirs, "../../.credentials")
                .expect_err("bad id")
                .code,
            "invalid_argument"
        );
        assert_eq!(
            subagent_read(&guard, &cache, &dirs, S1, "../x")
                .expect_err("bad id")
                .code,
            "invalid_argument"
        );
        assert_eq!(
            subagent_read(&guard, &cache, &dirs, S1, "missing")
                .expect_err("missing")
                .code,
            "not_found"
        );
        assert_eq!(
            session_read(
                &guard,
                &cache,
                "p",
                &dirs,
                "99999999-0000-0000-0000-000000000000"
            )
            .expect_err("missing")
            .code,
            "not_found"
        );
    }
}
